# Generated by Django 3.0.7 on 2020-07-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='Store', max_length=255),
            preserve_default=False,
        ),
    ]
