# Generated by Django 3.0.7 on 2020-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
