# Generated by Django 3.0.7 on 2020-06-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_food_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='status',
            new_name='stock',
        ),
    ]
