# Generated by Django 3.0.7 on 2020-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_auto_20200622_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(),
        ),
    ]
