# Generated by Django 3.0.7 on 2020-07-01 13:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_auto_20200622_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
