# Generated by Django 3.0.7 on 2020-07-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_name'),
        ('Food', '0006_auto_20200701_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Store'),
        ),
    ]
