# Generated by Django 3.0.7 on 2020-07-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20200702_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorder',
            name='status',
            field=models.IntegerField(choices=[('P', 'Processing'), ('C', 'Completed')], default='P'),
        ),
    ]
